# Generated by Django 2.2.16 on 2020-09-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200903_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game', models.TextField()),
                ('img_url', models.TextField()),
                ('totalplayers', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_players', models.IntegerField()),
                ('team_names', models.TextField()),
            ],
        ),
    ]
