# Generated by Django 2.2.16 on 2020-09-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_game_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teams',
            new_name='Team',
        ),
        migrations.AddField(
            model_name='game',
            name='function',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
